# Generated by Django 4.2.10 on 2024-02-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPuntosDeAccesoWifi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifiaccespoint',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
